version: "3.7"

services:
  whoami:
    image: emilevauge/whoami
    networks:
      default:
      routing:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
networks:
  default:
    internal: true
    driver: overlay
  routing:
    external: true