version: "3.7"

volumes:
  portainer:

services:
  caddy:
    image: abiosoft/caddy
    ports:
    - 80:80
    volumes:
    - ./caddy/Caddyfile:/etc/Caddyfile
    - ./caddy/.caddy:/root/.caddy
    networks:
      default:
      routing:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
      placement:
        constraints:
        - node.hostname == manager1
  portainer:
    image: portainer/portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data
    networks:
      default:
      routing:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
      placement:
        constraints:
        - node.hostname == manager1
networks:
  default:
    internal: true
    driver: overlay
  routing:
    external: true